Algoritmo "Função"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/06/2016
Var
// Seção de Declarações das variáveis 
a, b, res :inteiro

funcao soma (x,y: inteiro): inteiro
inicio
retorne x+y
fimfuncao

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia (a)
leia (b)
res <- soma (a,b)
escreval (res)


Fimalgoritmo